### ISSUE TITLE
Initial issues 

### ISSUE THREAD

**Issue by juanortega0410** [LaughingQuoll/Haystack#3]
iPhone X - 11.1.1 
Looks beautiful and working great!

1. Bluetooth toggle does not work consistently. Turns off but will not turn on. Needs to be toggled off/on to eventually work. The WiFi toggle is instant and fast. 

2. Completely kills JB tweaks in settings app. After opening and closing or tweaking haystack settings, not sure exactly when. Need to respring to get jb tweak settings, battery percent, noctisx, etc to show again in settings app. 

This is all I have ran into in the past 10 minutes.

**Comment by Quoll-io** [comment]
1. Thanks.

2. That's a preferenceloader bug.
