### ISSUE TITLE
Cannot get out of safe mode without uninstalling

### ISSUE THREAD

**Issue by mattrbeck** [LaughingQuoll/Haystack#4]
After installing Haystack and restarting the SpringBoard, I get stuck in safe mode. I cannot get out of safe mode until I uninstall Haystack.

iPhone 8
iOS 11.0.3
Installing Haystack 1.0.2 from packix.laughingquoll.net
No files in /var/mobile/Library/Preferences matching com.laughingquoll.haystack*

|User Tweaks|Expert Tweaks|
|-|-|
|APT 0.7 (apt-key)|Cephei|
|APT 0.7 Strict|IconSupport|
|APT 0.7 Strict (lib)|libpackageinfo|
|Base Structures|Link Identity Editor|
|Berkeley DB|Locale Profiles in UTF-8|
|BigBoss Icon Set|pincrush|
|Bourne-Again SHell|PreferenceLoader|
|bzip2|RocketBootstrap|
|Core Utilities|TechSupport Framework|
|Core Utilities (/bin)|UIKit Tools|
|Cydia Installer||
|Cydia Translations||
|Darwin Tools||
|Debian Packager||
|Debian Utilities||
|Diff Utilities||
|Find Utilities||
|GNU Privacy Guard||
|grep||
|gzip||
|Haystack||
|iPhone Firmware (/sbin)||
|New Curses||
|OpenSSH||
|OpenSSL
|Profile Directory
|sed
|shell-cmds
|Substitute
|Substrate Compatibility Layer
|system-cmds
|Tape Archive
|Tweak Injector
|XZ Utils

**Comment by FaZeIlLuMiNaTi** [comment]
Same issue occurring for me, iPhone 6s, 11.0.3. I’ve attached a crash report (although I’m not sure how relevant it is) from settings > privacy > analytics > analytics data.

Package list:
AdBlock for YouTube: 1.0.7
Anemone: 2.1.7-1
appinst (App Installer): 1.1
AppList: 1.5.14
AppSync Unified: 9.0
AutoShiftFix: 0.1
Base Structure: 1-4
basic-cmds: 55
BatteryPercentX [Public]: 0.0.9-8-7
betterFiveColumnHomescreen: 1.0.1
BigBoss Icon Set: 1.0
CanYouLikeNot: 1.0-1
Cephei: 1.12
Cercube for YouTube: 4.2.2.0
CertRemainTime: 2.3.4-2
ClearBadges3DTouch10: 1.0.1
clipme: 1.2-3
CocoaTop: 2.0.2
ColorBanners 2: 1.1.0
Cuttlefish: 1.0.3
Cydia Translations: 1.1.12
Cylinder: 1.0.6
Dank Zeppelin Logos: 1.0
DetailedCellularUsage: 2.1.1
DetailedPowerUsage: 1.0.1
DoubleTapLock [Public]: 0.0.3
Eclipse X (iOS 11): 5.0.5
Ext3nder Installer (iOS 11): 016-1
Filza File Manager 64-bit: 3.5.1-1
Fiona: 0.1
FiveIconDockXI: 0.0.1-20
Flame: 1.3
FlatFields: 0.0.7
htop: 2.1.0
i8Corners: 0.12
iCleaner Dark Theme: 1.0.2
iCleaner Pro: 7.7.0
IconSupport: 1.11.0-1
iOS 10 iCons Theme: 1.0
iOS 9 Lock Sound: 1.0-1
iOS Firmware: 11.0.3
iPhone Firmware (/sbin): 0-1
LetMeKnow: 1.2-1
libCercube: 1.0.8
libcolorpicker: 1.6-1
Liberty Lite: 0.2.0
libpackageinfo: 1.1.0.1-1
libSparkAppList: 0.0.4-1-2
libswift4: 4.0.3-3
Link Identity Editor: 2:1.2.2-coolstar
LittleX: 1.3.7
Locale Profiles in UTF-8: 1.0-1
NewTerm 2: 2.0\~beta3
NO PLS RECOVERY: 2.1.1
NoctisXI: 1.1.2
NoLargeTitles: 1.0-1
NoSharePlz: 1.0
NoSubstitute (Electra): 1.0-1
NotTodaySatan: 2.7.1
NudeKeys: 3.1
pincrush: 0.9.2-2
Play!: 0.30-20170829
PreferenceLoader: 2.2.4\~alpha1
Profile Directory: 0-2
PullToRespring: 1.2
RealCC: 0.0.4-1
RocketBootstrap: 1.0.6
Rooster: 1.0.0
Silo: 1.0.0-1+debug
SimpleLSiOS: 1.3.0-1
SnapchatNoClickbait: 0.0.2
Sonus: 3.0.2-3
SpectrePatch: 0.0.2
SpotClearOnClose: 1.0.0-1
SugarCane: 1.0.0
SwipeForMore: 1.1.7
SwipeSelection: 1.5.2-1
System Info: 2.0.0-1010+debug
TapTapFlip: 1.3.3
TapTime [Public]: 0.0.31
TechSupport Framework: 1.5.0.1-1
togglesafe: 1.0.2
True Art Theme: 1.4
TSS Saver: 1.2.0
Zeppelin: 2.1.0-12

[SpringBoard-2018-03-31-153458.zip](https://github.com/LaughingQuoll/Haystack/files/1865566/SpringBoard-2018-03-31-153458.zip)

**Comment by sirius247** [comment]
This happens to me as well. 

I'm on iPhone 8/iOS 11.0

**Comment by TheRealKeto** [comment]
Same issue here. It happened to me even back on the very early release (when it was called CCX). I'm wondering if it has to do with configuring a file that allows you to move your CC toggles (similar to what Silo does) on your filesystem.

**Comment by pcnk99** [comment]
I have exactly the same problem. iPhone 8;IOS 11.0

**Comment by Quoll-io** [comment]
This is a bug with iOS 11.0 I believe.

**Comment by sirius247** [comment]
Now what then?? Are you able to get around it? If not then what happens to us that paid for this?

Thanks...

**Comment by Quoll-io** [comment]
I need time to figure out the differences between 11.1 and 11.0 so I can fix this issue.

**Comment by mattrbeck** [comment]
Does this new label mean we're waiting for CrashReporter to be updated for iOS 11?

**Comment by FaZeIlLuMiNaTi** [comment]
Using rpetrich's [deviceconsole](https://github.com/rpetrich/deviceconsole), I was able to produce this crash log: [HaystackCrash.log](https://github.com/LaughingQuoll/Haystack/files/1885162/HaystackCrash.log). Not sure what use it could be to you @LaughingQuoll, but hopefully it will help while we wait for CrashReporter.

**Comment by Quoll-io** [comment]
@FaZeIlLuMiNaTi 

<Notice>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CCUIModularControlCenterOverlayViewController overlayBackgroundView]: unrecognized selector sent to instance 0x104126e00'

**Comment by Quoll-io** [comment]
This is very helpful thank you.

**Comment by Quoll-io** [comment]
Fixed
